### PR TITLE
Fix Problem with Javascript in Plone 5.1. latest

### PR DESCRIPTION
**Pull request by jensens**
For some reason the js-bundle did not work in Plone 5.1.4. 

imgpsh_fullsize 1

Recompiling it helped. 

While at it I fixed the dependencies in `metadata.xml` and cleaned up the buildout a bit.

### CODE REVIEW

**Comment by jensens** [comment]
Btw., @tmassman you use the collective namespace but the package is in your company repo. One would expect collective packages to live in the collective as its main location. What about deleting it here and keeping the canonical repo in collective?

**Comment by thomasmassmann** [comment]
@jensens, thanks. Could you fix the failing tests first, please?

**Comment by iham** [comment]
i invested more than a day to fix buildout, tests and learned about robot framework and fixed a bug in robotframework too.

i won't fix coverage and still need a release of this package on pypi.
@tmassman please think about @jensens and my wish to merge this to collective and add collective and me as maintainer on pypi too.
thank you!

**Comment by iham** [comment]
ah! you added me already to pypi - thank you :)

the next step would be moving it to collective. maybe @jensens can help with that.

**Comment by thomasmassmann** [comment]
I'm sorry but I will not accept this PR here. Too many fundamental things changed without being discussed before. I'm totally against the buildout structure as it is now (I have my best practices and a reason for it). That's also why most of my projects are not in the collective. You can release the project on PyPI, but please indicate it is a major change, so 1.0 would be ok for me. I will not move it to the collective, just keep on developing there and adjust the other files referencing this source if you wish.

I'm also against using patterns now for everything where absolutely not necessary, as it introduces more problems as it solves.

I will continue this project under my own, but using the `spirit` namespace. So this project will be renamed soon. Thanks for your work, though.

**Comment by jensens** [comment]
@iham, it is already in the collective. If @tmassman renames it here I think it may loose the connection to this repo and show up as the main repository. Not sure, so. If not its also not a problem to fork away with a collective version following a more Plonish way (like using patterns, unified buildout). To not confuse the people I would like to see a short note about the fork in the README.

I can understand @tmassman arguments, that is one reason why we put some of our stuff under the `bda.*` namespace in our @bluedynamics company organisation.

**Comment by thomasmassmann** [comment]
I will update this repo once the information in the readme of the collective fork is adjusted.

**Comment by iham** [comment]
@tmassman i can update the readme - what kind of adjustments do you propose?

**Comment by thomasmassmann** [comment]
Well, first of all I would adjust all links and point them to the collective repo and remove the rtd link is removed (I can remove the rtd from my account if you like).

**Pull request closed without merging**
